### ISSUE TITLE
No russian realms isnt working 

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/mega-alerts#32]
users have said this doesnt work

https://github.com/ff14-advanced-market-search/mega-alerts/blob/main/utils/mega_data_setup.py#L271-L277

https://github.com/ff14-advanced-market-search/mega-alerts/blob/main/utils/helpers.py#L19-L20

**Comment by Bencois** [comment]
NO_RUSSIAN_REALMS="true" does not work for me.

I've manually removed the Russion servers from the EU realm id.json to fix the issue.
https://wowpedia.fandom.com/wiki/Europe_region_realm_list_by_datacenter#Whirlwind-RU
I used this list to find the english names of the RU servers

**Comment by Bencois** [comment]
Used a clean EU real ID.json to recreate the issue.
The mentioned servers in the screenshot are RU servers:
![image](https://github.com/ff14-advanced-market-search/mega-alerts/assets/5656611/e58b9288-d188-4fcb-95ee-0aa3446d8ebf)

My Mega data.json
![image](https://github.com/ff14-advanced-market-search/mega-alerts/assets/5656611/2d27ed26-152c-473e-a705-4519e7c3ebb1)
